### ISSUE TITLE
Ability to resume a partial/aborted import?

### ISSUE THREAD

**Issue by eharris** [Ajnasz/sf2gh#1]
There doesn't seem to be a way to resume or restart a partial import, and the tool does not seem to check before creating duplicate tickets.  It just starts over and imports everything again.

**Comment by Ajnasz** [comment]
Hi @eharris 

Well, yes :)

This is an old project of mine, which never got mature enough to use it. :)

However the issue you mentioned can be solved relatively easily:
Either store the the saved changes locally in a db/file/whatever which can be fast, or store the data on the tickets and comments.
Personally I think the second approach would be nicer, but would slow down the import process and also it would reach the Github's rate limit faster which was a big pain as I remember.

Maybe I'll add this feature, but I can't promise it, so if you think a pr is welcome. :)

**Comment by Ajnasz** [comment]
Hey @eharris 

I spent some time to implement the feature you requested. I migrated [fluxbox](https://sourceforge.net/projects/fluxbox/) to github with more than 1100 issues, it looks good to me.
Can you try it please? :)

I also built it for a few platforms: https://github.com/Ajnasz/sf2gh/releases/tag/v1.0.0

**Comment by eharris** [comment]
I really appreciate your quick response on this, as well as willingness to support your old project, as I am not as comfortable hacking on Golang as you.  While I had mainly been concerned with resuming a one-time import/migration, this also seems like it might be possible to use this on a continuing basis to migrate "new" tickets/comments to the Github project if the SF project sees additional activity, would you see any potential problems with that?

I have tested the new version and these are my observations, apologies for these not being necessarily related with the original topic of this ticket.  The project I am testing with is `mp3splt`.

First the good:

* This new version seems to fix a problem I had been working toward tracking down where the same ticket was imported multiple times, and also that the process continued past the supposed end ticket number and had to be aborted manually.

Problems:

* The ticket comment creation doesn't seem to be avoiding duplicates.  Multiple runs creates multiple identical comments on tickets.
* The tickets seem to import in reverse-chronological order, where normal chronological would be more consistent and logical.  Github already orders tickets in reverse-chron order, so this makes the oldest tickets show up first which is undesirable.
* A simple abort with ^C doesn't work reliably (is this intentional?)

Other things that would simply be "nice-to-haves":

* Support doing multiple ticket types in the same run.  Currently it seems to only do "bugs" but I would also like to get "Feature Requests" and "Patches".
* I miss the `-debug` flag, as that was helpful in trying to see more details of what is happening  (I manually added some debug statements while testing)
* Some indication of comments within a ticket as they are imported (I added this for debugging)
* Link to original creator/commenter info page on Sourceforge, similar to how the tickets link back to the SF ticket
* Although the links to SF using http seem to work (automatically redirected), they probably should be https
* Microseconds on timestamps seems like overkill

**Comment by Ajnasz** [comment]
Hey @eharris 

Thank you for this nice list :) I was working on them and tried to fix or improve them.

> The ticket comment creation doesn't seem to be avoiding duplicates. Multiple runs creates multiple identical comments on tickets.

It must be fixed, I simply forgot to save the information if a comment was created.

> The tickets seem to import in reverse-chronological order, where normal chronological would be more consistent and logical. Github already orders tickets in reverse-chron order, so this makes the oldest tickets show up first which is undesirable.

That was a tricky one, since sourceforge is returning the issues in that order. So I made some trick: start from the last page and create the tickets in reverse order. In theory it must be good.

> A simple abort with ^C doesn't work reliably (is this intentional?)

It is intentional, because that is the way I could figure out to keep the integrity of the progress db. The program will exit after the last operation finished. If you want to foce close it, I suggest to use SIGTERM.

> Support doing multiple ticket types in the same run. Currently it seems to only do "bugs" but I would also like to get "Feature Requests" and "Patches".

Not in a simple run but in multiple runs you can do. I added a flag, called `category` - default to `bugs`. Use `patches` for example for patches. (Unfortunately I don't know what is it for "Feautre Requests").

> I miss the -debug flag, as that was helpful in trying to see more details of what is happening (I manually added some debug statements while testing)

Added back some debug information however it could e annoying :)

> Some indication of comments within a ticket as they are imported (I added this for debugging)
> Link to original creator/commenter info page on Sourceforge, similar to how the tickets link back to the SF ticket
> Although the links to SF using http seem to work (automatically redirected), they probably should be https
> Microseconds on timestamps seems like overkill

I changed from the manually constructed contents to use templates and added these informations to it. You can anytime create your own template (`-commentTemplate` and `-ticketTemplate` flags), here you can find examples: https://github.com/Ajnasz/sf2gh/tree/master/templates

**Comment by eharris** [comment]
@Ajnasz I am amazed and extremely appreciative at your speed and willingness to address these issues! Thank you!
I just submitted a pull request to add a few things I wanted, and do some documentation updates.

There does seem to be a problem with the comments though.  Those are missing the comment text, and the url is just the prefix as well.  The main ticket comment seems to be fine, just not the sub-comments.

**Comment by Ajnasz** [comment]
@eharris Thank you for your help. I fixed the comment template and also commented on the PR.

**Comment by eharris** [comment]
I consider this more than resolved.  Thank you!
